/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

new bool:abbw_hwx[MAXPLAYERS+1] = false;

public Plugin:myinfo = 
{
	name = "管理员领取红外线",
	author = "笨蛋海绵",
	description = "<- Description ->",
	version = "1.0",
	url = "QQ群：133102253"
}

public OnPluginStart()
{
	RegAdminCmd("sm_hwxon", Cmd_hwxon, ADMFLAG_ROOT, "管理员开启红外线");
	RegAdminCmd("sm_hwxoff", Cmd_hwxoff, ADMFLAG_ROOT, "管理员关闭红外线");
	
	
	HookEvent("player_use", 	Event_PlayerUse); 
}

public Action:Cmd_hwxon(client, args)
{
    if (IsClientInGame(client) && !IsFakeClient(client) && GetClientTeam(client) == 2)
    {
        abbw_hwx[client] = true;
        CheatCommand(client, "upgrade_add", "laser_sight");
        PrintToChat(client, "\x01[恭喜] \x05开启捡起武器自动红外线")
    } else {
        PrintToChat(client, "\x01[恭喜] \x05确保自己属于活着的幸存者")
    }

    return Plugin_Handled;
}

public Action:Cmd_hwxoff(client, args)
{
    if (IsClientInGame(client) && !IsFakeClient(client) && GetClientTeam(client) == 2)
    {
        abbw_hwx[client] = false;
        PrintToChat(client, "\x01[恭喜] \x05关闭捡起武器自动红外线")
    } else {
        PrintToChat(client, "\x01[恭喜] \x05确保自己属于活着的幸存者")
    }

    return Plugin_Handled;
}

public Action:Event_PlayerUse(Handle:hEvent, const String:name[], bool:dontBroadcast)
{
	new Client = GetClientOfUserId(GetEventInt(hEvent, "userid"));
	new entity = GetEventInt(hEvent, "targetid");
	decl String:classname[64];
	GetEdictClassname(entity, classname, 64);			
	if(StrContains(classname, "weapon_adrenaline")>=0 ||
		StrContains(classname, "weapon_defibrillator")>=0 ||
		StrContains(classname, "weapon_first_aid_kit")>=0 ||
		StrContains(classname, "weapon_pain_pills")>=0 ||
		StrContains(classname, "weapon_molotov")>=0 ||
		StrContains(classname, "weapon_pipe_bomb")>=0 ||
		StrContains(classname, "weapon_vomitjar")>=0 ||
		StrContains(classname, "weapon_gascan")>=0 ||
		StrContains(classname, "weapon_propanetank")>=0 ||
		StrContains(classname, "weapon_oxygentank")>=0 ||
		StrContains(classname, "weapon_upgradepack_explosive")>=0 ||
		StrContains(classname, "weapon_upgradepack_incendiary")>=0 ||
		StrContains(classname, "weapon_gnome")>=0 ||
		StrContains(classname, "weapon_fireworkcrate")>=0 ||
		StrContains(classname, "melee")>=0 || abbw_hwx[Client] == false)
	{
		
	}else{
		CheatCommand(Client, "upgrade_add", "laser_sight");
	}
	return Plugin_Continue;
}

stock CheatCommand(Client, const String:command[], const String:arguments[])
{
    if (!Client) return;
    new admindata = GetUserFlagBits(Client);
    SetUserFlagBits(Client, ADMFLAG_ROOT);
    new flags = GetCommandFlags(command);
    SetCommandFlags(command, flags & ~FCVAR_CHEAT);
    FakeClientCommand(Client, "%s %s", command, arguments);
    SetCommandFlags(command, flags);
    SetUserFlagBits(Client, admindata);
}
